# @package _global_

# Defaults for training for the PushT dataset as per https://github.com/real-stanford/diffusion_policy.
# Note: We do not track EMA model weights as we discovered it does not improve the results. See
#       https://github.com/huggingface/lerobot/pull/134 for more details.
hydra:
  run:
    dir: outputs/train/diffusion_ee_transfer_cube # todo
  job:
    name: default # todo

resume: false
device: cuda:0
use_amp: false
seed: 1000
dataset_repo_id: aloha_sim_ee_transfer_cube_scripted
dataset_root: data/
video_backend: pyav

wandb:
  enable: false
  # Set to true to disable saving an artifact despite save_checkpoint == True
  disable_artifact: true
  project: aloha
  notes: ""
  log_video: false

fps: 50
env:
  name: aloha
  task: AlohaEETransferCube-v0
  state_dim: 16
  action_dim: 16
  fps: ${fps}
  episode_length: 400
  gym:
    obs_type: pixels_agent_ee_pos
    render_mode: rgb_array

training:
  offline_steps: 2000
  online_steps: 0
  eval_freq: 2000
  save_freq: 100
  log_freq: 250
  save_model: true
  save_checkpoint: true
  num_workers: 1

  batch_size: 8                                    
  grad_clip_norm: 10
  lr: 1.0e-4
  lr_scheduler: cosine
  lr_warmup_steps: 500
  adam_betas: [0.95, 0.999]
  adam_eps: 1.0e-8
  adam_weight_decay: 1.0e-6
  online_steps_between_rollouts: 1
  
  delta_timestamps:
    observation.images.top: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, 1)]"
    observation.state: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, 1)]"
    action: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, 1 - ${policy.n_obs_steps} + ${policy.horizon})]"
  
  online_sampling_ratio: 0.5
  online_env_seed: ???
  
  image_transforms:
    enable: false
    # This is the maximum number of transforms (sampled from these below) that will be applied to each frame.
    # It's an integer in the interval [1, number of available transforms].
    max_num_transforms: 3
    # By default, transforms are applied in Torchvision's suggested order (shown below).
    # Set this to True to apply them in a random order.
    random_order: false
    brightness:
      weight: 1
      min_max: [0.8, 1.2]
    contrast:
      weight: 1
      min_max: [0.8, 1.2]
    saturation:
      weight: 1
      min_max: [0.5, 1.5]
    hue:
      weight: 1
      min_max: [-0.05, 0.05]
    sharpness:
      weight: 1
      min_max: [0.8, 1.2]

eval:
  n_episodes: 50
  batch_size: 10
  use_async_envs: false


policy:
  name: diffusion

  # Input / output structure.
  n_obs_steps: 2
  horizon: 16   
  n_action_steps: 8

  input_shapes:
    # TODO(rcadene, alexander-soare): add variables for height and width from the dataset/env?
    observation.images.top: [3, 480, 640]
    observation.state: ["${env.state_dim}"]
  output_shapes:
    action: ["${env.action_dim}"]

  # Normalization / Unnormalization
  input_normalization_modes:
    observation.images.top: mean_std
    observation.state: mean_std
  output_normalization_modes:
    action: mean_std

  # Architecture / modeling.
  # Vision backbone.
  vision_backbone: resnet18
  crop_shape: [480, 640]
  crop_is_random: True
  pretrained_backbone_weights: null
  use_group_norm: True
  spatial_softmax_num_keypoints: 32
  # Unet.
  down_dims: [512, 1024, 2048]
  kernel_size: 5
  n_groups: 8
  diffusion_step_embed_dim: 128
  use_film_scale_modulation: True
  # Noise scheduler.
  num_train_timesteps: 50
  beta_schedule: squaredcos_cap_v2
  beta_start: 0.0001
  beta_end: 0.02
  prediction_type: epsilon # epsilon / sample
  clip_sample: True
  clip_sample_range: 1.0

  # Inference
  num_inference_steps: 10

  # Loss computation
  do_mask_loss_for_padding: false